makes plasmacutters cost less to recharge
Monkestation/MonkeStation pull request #219
Opened 2022-03-24 03:05 UTC by Serxule

# About The Pull Request

simple PR changing some numbers to make plasma cutters cost less plasma to recharge

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
balance: NT decided to upgrade parts in plasmacutters, making them cost less to recharge

/:cl:

2022-03-24 03:16 UTC, nednaZ requested changes
Numbers look fine to me, the plasma cutter has always been a pain to actually charge up.
Just need the code comments to mark out that we have edited these sections locally.

2022-03-24 03:16 UTC, nednaZ commented on code/modules/projectiles/guns/energy/special.dm
> +		charge_multiplier = 5
```suggestion
		charge_multiplier = 5 // MonkeStation Edit
```

2022-03-24 03:16 UTC, nednaZ commented on code/modules/projectiles/guns/energy/special.dm
> +		charge_multiplier = 3
```suggestion
		charge_multiplier = 3 //MonkeStation Edit
```

2022-03-24 03:16 UTC, nednaZ commented on code/modules/projectiles/guns/energy/special.dm
> +		cell.give(100*charge_multiplier)
```suggestion
		cell.give(100*charge_multiplier) //MonkeStation Edit
```

2022-03-24 03:19 UTC, Serxule commented
didnt realize that, done

2022-03-26 18:12 UTC, nednaZ commented
Just leaving for reference.
1 ore is 30% charge on a regular cutter.
1 sheet is 50% charge on a regular cutter.

2022-03-26 18:13 UTC, merged