Lawyer Screms
Monkestation/MonkeStation pull request #220
Opened 2022-03-25 02:48 UTC by WonderPsycho

# About The Pull Request

adds in new funny alternate lawyer screams to many of the lawyers default clothes, both suit jackets and suits! (also useful for those who want to roleplay as Pheonix Wright or Makoto Neagi for the memes on station, i made your dreams come true)

## Why It's Good For The Game

Lawyer:OBJECTION! OBJECTION! OBJECTION! OBJECTION! OBJECTION! OBJECTION! OBJECTION! NO THAT'S WRONG!!

## Changelog

:cl:WonderPsycho
add:new shitposty Lawyer screams
/:cl:

2022-03-26 18:18 UTC, nednaZ requested changes
Audio quality on "NOTHATSWRONG1.ogg" and "NOTHATSWRONG2.ogg" is too low and has a lot of background music still in it.

You don't need to add the alternative scream to every outfit, just do it to the base item '/obj/item/clothing/under/rank/civilian/lawyer'

Please fix the spelling error in the folder name for readability. "Screams", not "Screms"

2022-03-26 22:24 UTC, WonderPsycho commented
> Audio quality on "NOTHATSWRONG1.ogg" and "NOTHATSWRONG2.ogg" is too low and has a lot of background music still in it.
> 
> You don't need to add the alternative scream to every outfit, just do it to the base item '/obj/item/clothing/under/rank/civilian/lawyer'
> 
> Please fix the spelling error in the folder name for readability. "Screams", not "Screms"

i intentionally named the folder "lawyer screms" as a joke, but i will change the name of the folder to "Lawyer Screams" for readability

2022-03-27 04:21 UTC, WonderPsycho commented
renamed the Lawyer Screms folder to Lawyer Screams for readability, and  changed the civilian.dm file to have it play sounds on the lawyer outfit base file instead of all variations of it, also fixed the audio of NOTHATSWRONG1.ogg and changed it to NoThatsWrong1New.ogg, also removed NOTHATSWRONG2.ogg cause it was unnecessary for to have that file since the DR video game series is lesser known then the Ace Attorney Series anyways

2022-03-27 04:27 UTC, WonderPsycho commented
oh jeez a single run test fail

2022-03-27 17:42 UTC, nednaZ requested changes
"NoThatsWrong1New.ogg" still sounds really bad.
Just get rid of it at this point and keep the objections.

2022-03-27 17:42 UTC, nednaZ commented on monkestation/code/modules/clothing/suits/jobs.dm
> +/obj/item/clothing/suit/toggle/lawyer/purple
You don't need this one at all, since the parent type covers it

2022-03-27 17:42 UTC, nednaZ commented on monkestation/code/modules/clothing/suits/jobs.dm
> +/obj/item/clothing/suit/toggle/lawyer/black
Nor this one

2022-03-30 22:05 UTC, merged