Small circuitry tweaks
Monkestation/MonkeStation pull request #417
Opened 2022-05-31 05:35 UTC by Oricana-16

# About The Pull Request

(Re-requesting because I figured out branches on my fork. If there was a cleaner way to do this w/ the requests, my bad)

Made the Modular Assembly shell attachable to wires (i.e. Door wires, grenade wires), letting you do more fun things with circuitry/this shell that feels reasonable to have.

Made the Sound Synthesizer able to be used as a circuit shell (cooldown still exists w/ circuits so you can only spam the normal amount) (Inputs: What sound to play, play the sound. Outputs: When a sound is played)

Quantum Spin Inverters are also a shell, I don't know how often they'd come up, though fun can still be had with them when they do. (Inputs: Activate the QSI, Break the QSI's link. Outputs: When the QSI teleports)

And the big one, Secways are also shells now. They are set up similarly to Drones, letting you control their movement. The real star of this show is the MMI component, letting you make sentient Secways. In fact you can put mmi components in all of these, which can make for some really fun gimmicks and bits. (Inputs: Move North, West, South, East)

## Why It's Good For The Game

Gives circuitry some more fun uses, even if its not a lot more.

## Changelog

:cl:
add: Sound Synthesizers, QSIs, and Secways are now able to be circuit shells
add: Modular Assemblies can now be attached to wires
/:cl:

2022-05-31 17:09 UTC, nednaZ commented
Is this ported from anywhere?
If so, please link it in the about section

2022-05-31 17:19 UTC, Oricana-16 commented
> Is this ported from anywhere?
This isn't ported from anywhere, I just wanted something changed and more shells.

I did find this though (https://github.com/tgstation/tgstation/pull/62307) which added assemblies to tg With the connecting to wires thing. I don't know if I should link it cause that one is adding assemblies with the thing and mine is modifying it. Or would that still count as a port?

2022-06-01 17:18 UTC, nednaZ requested changes
Looks like it could be fun

2022-06-01 17:18 UTC, nednaZ commented on code/game/objects/items/devices/sound_synth.dm
> +			var/list/assblast = params2list(shell?.sound_list[soundtoplay.input_value])
As much as we know it will be used for this, needs a better variable name.

2022-06-01 17:18 UTC, nednaZ commented on code/modules/vehicles/secway.dm
> +	var/move_delay = 0.75
This variable is unchanged, so make it a define and undefine instead.

2022-06-03 18:55 UTC, nednaZ commented
I need a methodology to actually test this, as I do not know new circuitry at all.
If you can set up a few examples of how it is meant to work, as well as document what options the sound circuit has, I can actually test it.

2022-06-03 19:57 UTC, Oricana-16 commented
https://www.youtube.com/watch?v=L8zrV92SOSc 
Heres a video of me going through everything I added. The Sound Synth sound list it everything it can play normally

<details>
<summary>Sound Synth List</summary>

- Honk
- Applause
- Laughter
- Rimshot
- Trombone
- Airhorn
- Alert
- Boom
- Boom from Afar
- Bubbles
- Countdown
- Creepy Whisper
- Ding
- Bwoink
- Double Beep
- Flush
- Kawaii
- Startup
- Welding Noises
- Short Slide Whistle
- Long Slide Whistle
- YEET
- Time Stop
- Click
- Booing
- Awwing
- Gasping
- Oohing

</details>

2022-06-03 21:55 UTC, nednaZ approved these changes
Looks fine to me.
I'll have to actually start playing with these circuits a bit

2022-06-03 21:55 UTC, merged