Hardlight Spear traitor item
Monkestation/MonkeStation pull request #421
Opened 2022-05-31 21:55 UTC by Oricana-16

# About The Pull Request

Adds the Hardlight Spear implant, a 10 tc traitor item that lets you summon a spear every 30 seconds. The spear deals quite a bit of damage, and disappears once it gets thrown (whether you hit or not, there are some cases where the spear might stay though, usually when you get the killing blow on something). If you use it as a melee weapon, it does slightly more damage than a normal spear, but much less than throwing it does.

## Why It's Good For The Game

Adds a more conspicuous (or inconspicuous depending on how you play it.), big damage throwing item for traitors, that you dont need to/cant spam with at all, and also energy spears are just sick af.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

![HoldingPhoto](https://user-images.githubusercontent.com/99915170/171290007-55103484-9128-451c-8b3a-99b2ba381017.png)

![ImplantPhoto](https://user-images.githubusercontent.com/99915170/171290014-985f41ac-d906-4c1a-9cc4-d3c3262f31d8.png)

![UplinkPhoto](https://user-images.githubusercontent.com/99915170/171290027-177a12a3-b7f3-4938-a0eb-3f59944af025.png)

</details>

## Changelog

:cl:
add: Added Hardlight Spear implant (10tc) for traitors.
imageadd: added a hardlight spear icon for both an implant button icon and an item icon
/:cl:

2022-06-01 16:59 UTC, nednaZ requested changes
Looks like it will be a fun item, just needs some work.

2022-06-01 16:59 UTC, nednaZ commented on code/game/objects/items/devices/sound_synth.dm
> +        https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/items/devices/soundsynth.dm
Why was this edited?

2022-06-01 16:59 UTC, nednaZ commented on monkestation/code/game/objects/items/implants/implant_hardspear.dm
> +	var/obj/item/spear/awesomespear
You can use the typepath of the hard light spear directly.
new var/obj/item/spear/hardlightspear/summoned_spear(loc) for example.

Also, change the variable name to something more relevant for readability

2022-06-01 16:59 UTC, nednaZ commented on monkestation/code/game/objects/items/implants/implant_hardspear.dm
> +/obj/item/spear/hardlightspear
I prefer snake_case

2022-06-01 16:59 UTC, nednaZ commented on monkestation/code/game/objects/items/implants/implant_hardspear.dm
> +	desc = "A glass case containing a freedom implant."
Inaccurate description

2022-06-01 16:59 UTC, nednaZ commented on monkestation/code/game/objects/items/implants/implant_hardspear.dm
> +		if(is_hot() && isliving(hit_atom))
Why is it checking for heat?

2022-06-01 16:59 UTC, nednaZ commented on monkestation/code/game/objects/items/implants/implant_hardspear.dm
> +	if(imp_in.put_in_hands(awesomespear))
You can have this proc delete the spear on fail

2022-06-03 18:30 UTC, nednaZ requested changes
I like the overall design, though it strangely feels weak.
I'd like a sound effect that plays upon summoning the spear and maybe a reduction in cooldown to 20 seconds.

2022-06-03 18:55 UTC, Oricana-16 commented
> I'd like a sound effect that plays upon summoning the spear

Do you have any recommendations for the sound? I think the e-sword turning on (saberon.ogg) seems fine, but I'm not sure if that'd be too confusing or anything if they use the same sound.

2022-06-03 19:04 UTC, Oricana-16 commented
I lowered the cooldown and made the sound play. If you think the sound should be different lmk but otherwise 👍.

2022-06-03 21:46 UTC, nednaZ approved these changes
I like it.
Maybe in the future it will need tweaking, but I think it's good enough to use for now.

2022-06-03 21:52 UTC, merged