Start of TG's Food system update
Monkestation/MonkeStation pull request #466
Opened 2022-06-12 06:57 UTC by dwasint

# About The Pull Request

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-06-14 16:26 UTC, dwasint commented on code/__DEFINES/layers.dm
> -#define ABOVE_HUD_LAYER 23
Why was this even a thing to begin with? everything already defaults to being above the hud layer

2022-06-18 21:39 UTC, NiftyRyanyan commented
Are you fully porting https://github.com/tgstation/tgstation/pull/67156 and https://github.com/vgstation-coders/vgstation13/pull/30359
It’s hard to check as you are changing 493 files in a single PR. You should consider spitting this PR up so people can see what they actually want ported instead of a massive fuck off PR.

2022-06-18 21:43 UTC, dwasint commented
> Are you fully porting [tgstation/tgstation#67156](https://github.com/tgstation/tgstation/pull/67156) and [vgstation-coders/vgstation13#30359](https://github.com/vgstation-coders/vgstation13/pull/30359) It’s hard to check as you are changing 493 files in a single PR. You should consider spitting this PR up so people can see what they actually want ported instead of a massive fuck off PR.

its only porting the alt click menu from goofkitchen, and just the sprites and idea from the condiments update

2022-06-19 18:41 UTC, nednaZ requested changes
Some issues, but nothing too critical.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pastries.dm
> +/obj/item/food/icecream
Might be in the wrong section?

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pie.dm
> +/* FOR NOW THIS WILL PROBABLY NEED SNOWFLAKE CODE
If this has been unused, go ahead and get rid of it.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/margherita/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/meat/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/mushroom/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/vegetable/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/donkpocket/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/dank/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/sassysage/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/pineapple/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/pizza.dm
> +/obj/item/food/pizza/arnold/Initialize()
Redundant due to the base typepath having a generic method, would actually create double.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/salad.dm
> +/obj/item/food/salad/oatmeal
Why is this a salad? Weird

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/salad.dm
> +/obj/item/reagent_containers/glass/bowl
Shift these to the top, they're base parts of the salad

2022-06-19 18:41 UTC, nednaZ commented on code/modules/food_and_drinks/food/sandwhichtoast.dm
> +/obj/item/food/sandwich
Issue with filename, "sandwhich" is misspelled.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/research/xenobiology/crossbreeding/_misc.dm
> +/obj/item/food/rationpack
I think this is a double definition, saw it in misc too.

2022-06-19 18:41 UTC, nednaZ commented on code/modules/vending/drinnerware.dm
>  					/obj/item/clothing/suit/apron/chef = 2,
Misspelling in the filename. "drinnerware"

2022-06-19 22:52 UTC, dwasint commented on code/datums/components/edibles.dm
> +/datum/component/edible/proc/show_radial_recipes(atom/parent_atom, mob/user)
it was a test that i forgot to remove, this was testing alt click menu for everything not just foods

2022-06-19 22:55 UTC, dwasint commented on code/datums/mood_events/generic_positive_events.dm
> +	mood_change = 50
you need to be an abductor and eat peanut butter for this so quite rare

2022-06-19 22:56 UTC, dwasint commented on code/game/machinery/computer/chef_orders/order_datum.dm
> +/datum/orderable_item
it would type path error out if we didn't have it i believe

2022-06-19 23:05 UTC, dwasint commented on code/modules/food_and_drinks/food/egg.dm
> +	if(istype(W, /obj/item/kitchen/fork))
maybe in a future pr, as this is a general interaction already with plates

2022-06-19 23:07 UTC, dwasint commented on code/modules/food_and_drinks/food/meat.dm
> +//Not only meat, actually, but also snacks that are almost meat, such as fish meat or tofu
for clarity sake i think its better off the way it is now, i can resort this with things like seafood however

2022-06-19 23:49 UTC, dwasint commented on code/modules/food_and_drinks/food/meat.dm
> +/obj/item/food/sausage/MakeProcessable()
no it opens a radial menu

2022-06-19 23:57 UTC, nednaZ commented
It's ready for test merging, I'd say.

2022-06-19 23:58 UTC, dwasint commented
> It's ready for test merging, I'd say.

oh yea baby

2022-06-26 02:02 UTC, nednaZ commented
After a good week of testing, it all seems to be good.

2022-06-26 02:02 UTC, merged