Adds the admin only Ratvarian escape shuttle and some minor fixes to my modular bars.
Monkestation/MonkeStation pull request #471
Opened 2022-06-14 02:25 UTC by wraith-54321

# About The Pull Request

Adds a new admin only escape shuttle and fixes some minor issues with some of the modular bars I added.

## Why It's Good For The Game

Clock cult shuttle to go along with the blood cult shuttle, and fixes are generally good.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

The escape shuttle

![Screenshot (183)](https://user-images.githubusercontent.com/69217972/173479589-f86be456-c475-480d-9414-15c89d9b8675.png)

</details>

## Changelog

:cl:
add: New admin only Ratvarian escape shuttle
fix: Added grills to the clockwork bar windows
fix: Removed duplicate chairs in the magical bar
/:cl:

2022-06-14 17:16 UTC, nednaZ requested changes
The shuttle section should have seats.
The engines are very weird and uneven for both sides.
Needs some form of brig section to make it fully usable.
Get rid of two of the clockwork warriors and the strangely placed pasta.

2022-06-14 21:22 UTC, wraith-54321 commented on monkestation/code/datums/shuttles.dm
> +	credit_cost = 10000
The pasta is a reference to the ark which gives pasta if you use a fork on it, might take it down to just one. The brig is the room with the observation consoles.

2022-06-14 21:30 UTC, wraith-54321 commented on monkestation/code/datums/shuttles.dm
> +	credit_cost = 10000
The cogscarabs are shells due to the fact that spawning in the mob itself runtimes for some reason, however they cant do much besides build unless Reebe is loaded

2022-06-14 21:49 UTC, wraith-54321 commented on monkestation/code/datums/shuttles.dm
> +	credit_cost = 10000
I added a screenshot of the new version of the shuttle to the screenshots section.

2022-06-15 20:37 UTC, wraith-54321 commented
The cogscarabs need them to be able to unlock defense buildings as I dont know any other way to give them some cogs and I dont know what you mean about them not having time to add gears.

2022-06-15 21:20 UTC, nednaZ commented
The balloon that gives ghost roles to the cogscarabs only activates about 30 seconds before the shuttle arrives.
The scarabs have less than ten seconds before shuttle arrival, so there is zero time to build defenses or get cogs into the APCs.

2022-06-15 23:03 UTC, wraith-54321 commented
As I said here

> The cogscarabs are shells due to the fact that spawning in the mob itself runtimes for some reason

The cogscarabs are shells and can be entered by ghosts as a role, part of the gimmick is they can build up defenses before the shuttle arrives like on reebe, the shuttle has a wall of servant blockers around the entire area they can walk around in so they cant get out.

2022-06-16 16:18 UTC, nednaZ approved these changes
The APC justification makes sense, even if it's a bit weird in appearances.
Worth trying this shuttle out

2022-06-16 16:18 UTC, merged