Adds a Nudist Quirk
Monkestation/MonkeStation pull request #506
Opened 2022-06-30 04:15 UTC by MilkForever

# About The Pull Request
Adds a new neutral quirk called "Nudist", this quirk gives you an invisible jumpsuit in your backpack that you can wear, as the name suggests, its a jumpsuit that's becomes invisible when worn, doesn't actually make you invisible.

It still behaves like a normal jumpsuit, so you still have pockets, suit sensors, a belt and an ID card slot.

Special thanks to dwasint for helping me to get the jumpsuit to spawn in backpacks.

## Why It's Good For The Game
I've seen several people asking for a Nudist Quirk so here we are, it doesn't impact gameplay and it's more for customization than anything else.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/96450841/176590991-579ba9f7-f773-402d-ba17-a165d9e5a4d1.png)
</details>

## Changelog

:cl:
add: Added the Nudist Quirk! This is a neutral quirk that gives you an invisible jumpsuit, for those who don't like clothing.
/:cl:

2022-06-30 05:25 UTC, Zonespace27 requested changes
as much as i dislike this quirk in its entirety for more reasons than one (not that i can do anything about it), code review

2022-06-30 05:25 UTC, Zonespace27 commented on code/datums/traits/neutral.dm
> +/datum/quirk/nudist
this can be modularized

2022-06-30 05:25 UTC, Zonespace27 commented on code/datums/traits/neutral.dm
> +    var/mob/living/carbon/human/H = quirk_holder
one letter vars bad

2022-06-30 05:25 UTC, Zonespace27 commented on code/modules/clothing/under/miscellaneous.dm
> +/obj/item/clothing/under/invisible
this can be modularized

2022-06-30 05:25 UTC, Zonespace27 commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "Some sort of jumpsuit that dissapears when worn, but still behaves as a normal jumpsuit."
```suggestion
	desc = "Some sort of jumpsuit that disappears when worn, but still behaves as a normal jumpsuit."
```

2022-06-30 06:13 UTC, MilkForever commented
Alright, let me see if i can uh, modularize this so its in the monkestation folder, i think that's ideal.

2022-06-30 18:55 UTC, MilkForever commented
Wait, dang. im gonna draft this for now.

2022-06-30 19:09 UTC, MilkForever commented
Okay the checks passed now, but im still not sure if this is ready.

2022-07-01 17:04 UTC, nednaZ requested changes

2022-07-01 20:20 UTC, MilkForever commented on monkestation/code/datums/traits/neutral.dm
> +    person.equip_in_one_of_slots(clothing , slots , qdel_on_fail = TRUE)
Re-added the gain_text now.

2022-07-01 20:38 UTC, nednaZ approved these changes
I'm willing to give this a try, only because Ook has requested this quirk.

2022-07-01 20:38 UTC, merged