Tile QoL changes More to come in sister pr's
Monkestation/MonkeStation pull request #513
Opened 2022-07-04 00:04 UTC by dwasint

# About The Pull Request
Splitting this into 2+ pr's as things like neon carpets are 100 files changed alone, and tileing 2 is 70
Adds various QoL changes for tiles, like tile sprayer for decals, glass tiles, and added transparency flag for material datums (not currently used)
Also ports over asset caching helps load times.
PRS USED:
https://github.com/tgstation/tgstation/pull/63503
https://github.com/tgstation/tgstation/pull/54184
https://github.com/tgstation/tgstation/pull/54233
https://github.com/tgstation/tgstation/pull/66301
https://github.com/tgstation/tgstation/pull/49402  <-- Only the turf additions
https://github.com/tgstation/tgstation/pull/54250
https://github.com/tgstation/tgstation/pull/62890
https://github.com/tgstation/tgstation/pull/67449

## Why It's Good For The Game
More variety for building and mapping

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-07-23 19:03 UTC, nednaZ requested changes
Not seeing anything major.
Will need to test it when I get a chance

2022-07-23 19:03 UTC, nednaZ commented on code/game/turfs/open/space/space.dm
> +	var/turf/T = SSmapping.get_turf_above(src)
One letter variable

2022-08-07 03:41 UTC, NanoCats commented
Is it deliberate that you can't print Toner cartridges?

Autolathe or Protolathe on TG IIRC

2022-08-08 05:13 UTC, nednaZ commented
Only request is that you do add a method to create or get more of those toner cartridges, otherwise you'll just have to print a new sprayer every time it runs out.

2022-08-08 22:58 UTC, nednaZ approved these changes
Looks good to me.
Tests have shown no issues.

2022-08-08 23:00 UTC, merged