Adds a(nother) slick cowboy hat!
Monkestation/MonkeStation pull request #531
Opened 2022-07-11 00:06 UTC by etherware-novice

# About The Pull Request
Adds a sweet new cowboy hat to the clothesmate to make it more accessible to the crew to do cool showdowns

## Why It's Good For The Game
More roleplay power being able to buy a hat if you want

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![cowhat_vend](https://user-images.githubusercontent.com/73374039/178167382-9c8bc298-08b0-4a4f-bb5c-fda9f45d17ca.png)

![cowhat_floor](https://user-images.githubusercontent.com/73374039/178167351-584a0985-682e-4e0e-8604-0148a2477c00.png)

![cowhat_wear](https://user-images.githubusercontent.com/73374039/178167363-6e812acc-f80f-4bde-878a-bbab4c0839b2.png)

</details>

## Changelog

:cl:
:add: added the cowboy hat(?) item
:tweak: added the cowboy hat(?) to the clothemate
/:cl:

2022-07-11 19:26 UTC, nednaZ commented
You need to update your Master branch. This PR modifies catgloves.

2022-07-11 23:20 UTC, nednaZ requested changes
Don't put the icon changes in the base folders.
Use the monkestation module file for it.

2022-07-11 23:20 UTC, nednaZ commented on code/modules/vending/clothesmate.dm
> +					/obj/item/clothing/head/cowboydiscount = 3,  // for low budget "town aint big enough" scenes!
The comment should say that it is a monkestation edit.

2022-07-11 23:20 UTC, nednaZ commented on code/modules/clothing/head/misc.dm
> +/obj/item/clothing/head/cowboydiscount
Use snake_case for readability.
```suggestion
/obj/item/clothing/head/cowboy_discount
```

2022-07-11 23:20 UTC, nednaZ commented on code/modules/clothing/head/misc.dm
> +	name = "cowboy hat(?)"
Just give it a regular name
```suggestion
	name = "cowboy hat"
```

2022-07-12 00:13 UTC, etherware-novice commented
> Don't put the icon changes in the base folders.
> 
> Use the monkestation module file for it.

im having issues getting the human worn sprite working properly, which file do i put it in?

2022-07-12 19:55 UTC, Zonespace27 commented
> > Don't put the icon changes in the base folders.
> > Use the monkestation module file for it.
> 
> im having issues getting the human worn sprite working properly, which file do i put it in?

you can VV it in-game to see what icon file it uses for worn objects

2022-07-12 23:04 UTC, etherware-novice commented
whats vving it?
> > > Don't put the icon changes in the base folders.
> 
> > > Use the monkestation module file for it.
> 
> > 
> 
> > im having issues getting the human worn sprite working properly, which file do i put it in?
> 
> 
> 
> you can VV it in-game to see what icon file it uses for worn objects

2022-07-14 22:43 UTC, Zonespace27 commented
> what's VVing it?

View Variables

2022-07-15 17:56 UTC, nednaZ requested changes
Your files are a mess here.
You're modifying the original files, as well as the new files.
Somehow you're reducing the file size on the inhand files, which means you've removed something.

Quality of the sprite seems pretty poor, the item sprite itself is incredibly oversized.

2022-07-15 17:56 UTC, nednaZ commented on monkestation/code/modules/clothing/head/misc.dm
> +/obj/item/clothing/head/cowboy_discount
Wrong location for this.
I'd suggest checking the file structure for similar hats.

2022-07-15 19:22 UTC, etherware-novice commented
you know what i give up i give up

2022-07-15 19:22 UTC, closed without merging