Adds a Diagnostic Welding HUD for roboticists
Monkestation/MonkeStation pull request #535
Opened 2022-07-11 19:08 UTC by etherware-novice

# About The Pull Request
Adds a new hud type, being a combination of a diagnostic hud and welding shield. The welding shield part can be "pushed down" to quickly weld off items.

## Why It's Good For The Game
Roboticists currently have to use both the welding shield and diagnostic hud frequently to do their job well, which can be somewhat annoying if you want or need to use the head slot for other gear. This pr would give Roboticists a new option for optimal productivity.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![diagweld_floor](https://user-images.githubusercontent.com/73374039/178339810-65d21497-9b3a-4a0d-a4d4-3c26a5428f6a.png)

![diagweld_research](https://user-images.githubusercontent.com/73374039/178339826-5de688b4-4e28-4236-8c70-27aa337d04c8.png)

![diagweld_work](https://user-images.githubusercontent.com/73374039/178339830-bf143c45-9e3a-4b59-9251-f08facb5a44c.png)

</details>

## Changelog

:cl:
add: Added Diagnostic Welding HUD
:tweak: Added Diag-Weld HUD to the "Night Vision HUD" research node
:tweak: Added Diag-Weld HUD to the RoboDrobe as a premium item
/:cl:

2022-07-11 19:26 UTC, nednaZ commented
You need to update your Master branch. This PR modifies catgloves.

2022-07-11 19:26 UTC, nednaZ commented
You need to update your Master branch. This PR modifies catgloves.

2022-07-11 19:57 UTC, etherware-novice commented
> You need to update your Master branch. This PR modifies catgloves.

how do i do that?

2022-07-11 23:29 UTC, nednaZ commented on code/modules/research/designs/misc_designs.dm
> +/datum/design/diagnostic_hud_weld
Needs to go into the monkestation modular folder

2022-07-11 23:34 UTC, nednaZ commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("health_hud_night", "security_hud_night", "diagnostic_hud_night", "diagnostic_hud_weld", "night_visision_goggles", "nvgmesons")
Night vision tech seems like an odd place for it.

Also, put a comment at the end that there is a monkestation edit.

2022-07-11 23:35 UTC, nednaZ commented on code/modules/vending/wardrobes.dm
> +	premium = list ( /obj/item/clothing/glasses/hud/diagnostic/weld = 1 )
No, this is a tech item and should be produced only

2022-07-12 00:01 UTC, etherware-novice commented
> I'm unsure about the balance of this one.
> 
> Glasses that can be printed and provide flash protection with zero penalty may not work.
> 
> 
> 
> Icons needs to be in the monkestation module folders

it only provides flash protection when down, similar to standard welding equipment. it also requires quite a bit of research to unlock (night vision hud)

2022-07-12 01:56 UTC, dwasint commented on code/modules/clothing/glasses/hud.dm
> +	weldingvisortoggle(user)
weldingvisortoggle is defined in /obj/item/clothing/glasses? and the actual proc is in /obj/item/clothing

2022-07-12 01:57 UTC, dwasint commented on code/modules/clothing/glasses/hud.dm
> +	flash_protect = 2
weldingvisortoggle invert that

2022-07-12 02:46 UTC, Serxule commented
i mean the diagnostic hud implant already exists, combined with welding shield eyes, and they could also just use a welding helmet (which most do since goggles arent common)

2022-07-12 19:53 UTC, Zonespace27 requested changes

2022-07-12 19:53 UTC, Zonespace27 commented on code/modules/clothing/glasses/hud.dm
> +
why whitespace

2022-07-12 19:53 UTC, Zonespace27 commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("health_hud_night", "security_hud_night", "diagnostic_hud_night", "diagnostic_hud_weld", "night_visision_goggles", "nvgmesons")  // monkestation edit
this has nothing to do with nightvision, put it elsewhere

2022-07-12 19:53 UTC, Zonespace27 commented on monkestation/code/modules/research/designs/misc_designs.dm
> +
```suggestion
```

2022-07-14 22:32 UTC, Zonespace27 requested changes

2022-07-14 22:50 UTC, etherware-novice commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("ci-nutriment", "ci-breather", "ci-gloweyes", "ci-welding", "ci-medhud", "ci-sechud", "ci-diaghud", "ci-lighter", "diagnostic_hud_weld") // MONKE EDIT - added ci-lighter (and diag
which section would you like me to put it in?

2022-07-15 18:03 UTC, nednaZ commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("ci-nutriment", "ci-breather", "ci-gloweyes", "ci-welding", "ci-medhud", "ci-sechud", "ci-diaghud", "ci-lighter", "diagnostic_hud_weld") // MONKE EDIT - added ci-lighter (and diag
My suggestion would be "Experimental Tools"

2022-07-15 18:04 UTC, nednaZ requested changes
No worn icon, needs some indication that they are flashproof.

2022-07-17 18:52 UTC, nednaZ approved these changes
Looks good to me.

2022-07-17 18:52 UTC, merged