Janitor Lightreplacer replaces at a distance
Monkestation/MonkeStation pull request #536
Opened 2022-07-11 21:48 UTC by etherware-novice

# About The Pull Request
Edits the Light Replacer to work at a distance, using the same sfx and visuals as the Bluespace RPED 

## Why It's Good For The Game
Makes janitors job just a touch easier, as you dont need to waste time getting the crew to let you into restricted areas to replace lights as much. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
tweak: made the light replacer work through walls
/:cl:

2022-07-11 22:57 UTC, nednaZ commented
This has the catgloves change in it as well.
Update your master branch.

2022-07-11 22:58 UTC, etherware-novice commented
> This has the catgloves change in it as well.
> 
> Update your master branch.

how do i update the master branch??

2022-07-11 23:37 UTC, nednaZ commented
> how do i update the master branch??
Go to your local branch in VSC and hit update.

2022-07-12 02:40 UTC, etherware-novice commented
> > how do i update the master branch??
> > Go to your local branch in VSC and hit update.

please help i tried but it didnt say there were any changes to commit

2022-07-12 02:47 UTC, Serxule commented
probably have this be an upgrade, bluespace light replacer, like the bluespace rped

2022-07-12 19:51 UTC, Zonespace27 requested changes

2022-07-12 23:00 UTC, etherware-novice commented on code/game/objects/items/devices/lightreplacer.dm
> +
it was stuff i had added then subsequently removed i dont know how to get rid of it its fine-

2022-07-12 23:03 UTC, etherware-novice commented on code/game/objects/items/devices/lightreplacer.dm
> +//monkestation edit  (using brped)
i thought i was supposed to mark monkeststion edits thats what zanden said

2022-07-15 18:15 UTC, nednaZ requested changes
It works, but doesn't tell the user that there is already a functioning bulb in the light unless up close.

2022-07-15 18:15 UTC, nednaZ commented on code/game/objects/items/devices/lightreplacer.dm
> +		attack_self(itemtarget)
There is a dedicated proc for this. "ReplaceLight"

2022-07-15 18:15 UTC, nednaZ commented on code/game/objects/items/devices/lightreplacer.dm
> +//monkestation edit  (using brped)
Mark both the beginning and end of monkestation edit blocks with comments.

2022-07-15 18:15 UTC, nednaZ commented on code/game/objects/items/devices/lightreplacer.dm
> +/obj/item/lightreplacer/afterattack(obj/item/itemtarget, mob/living/user)
You have this double defined.
Make it work in the already existing afterattack proc.

2022-07-15 18:15 UTC, nednaZ commented on code/game/objects/items/devices/lightreplacer.dm
> +		user.Beam(itemtarget, icon_state = "rped_upgrade", time = 5)
Only play the beam and sound if at a distance, currently it does so even up close.

2022-07-19 03:44 UTC, closed without merging