Vent Clog Maxes
Monkestation/MonkeStation pull request #537
Opened 2022-07-11 23:36 UTC by Oricana-16

# About The Pull Request

Puts maxes on the vent clog event based on how many vents are in the map (Threatening 50%, Catastrophic 25%)

## Why It's Good For The Game

Makes less lag, causes less of a complete disaster, and more control over events is always nice

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Threatening
![image](https://user-images.githubusercontent.com/99915170/178375767-6c6da52a-9c6a-415c-8004-6669a71a4ca6.png)

Catastrophic
![image](https://user-images.githubusercontent.com/99915170/178375770-62ccf7c4-2bc2-4946-ae4a-478b57abad8b.png)

</details>

## Changelog

:cl:
tweak: made the more dangerous vent clogs only use some of the available vents
/:cl:

2022-07-11 23:41 UTC, nednaZ requested changes

2022-07-11 23:41 UTC, nednaZ commented on code/modules/events/vent_clog.dm
> +	var/use_all_vents = TRUE //Should it use every vent
Don't even bother with having it use all vents.

2022-07-11 23:41 UTC, nednaZ commented on code/modules/events/vent_clog.dm
> +	var/vent_percentage = 1 //How many vents it should use (0.5 = 50%)
Too many vents.
Bring the default down to about 25%

2022-07-11 23:41 UTC, nednaZ commented on code/modules/events/vent_clog.dm
> +	vent_percentage = 0.5
I'd say this should be about 15%

2022-07-11 23:41 UTC, nednaZ commented on code/modules/events/vent_clog.dm
> +	vent_percentage = 0.25
And this should be about 5%

2022-07-11 23:41 UTC, nednaZ commented on code/modules/events/vent_clog.dm
>  	reagentsAmount = 1250
Your PR isn't addressing the amount of fluids in each vent.
I'd suggest 300/500/700

2022-07-11 23:46 UTC, Oricana-16 commented
💥all done

2022-07-12 00:01 UTC, nednaZ approved these changes
Looks good to me

2022-07-12 00:01 UTC, merged