roundstart snails
Monkestation/MonkeStation pull request #538
Opened 2022-07-12 04:28 UTC by dwasint

# About The Pull Request

## Why It's Good For The Game
👎 saul wants them

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
nerfs:snail crawl speed makes it normal
adds: round start snails
/:cl:

2022-07-12 04:38 UTC, lmenvs commented
cringe

2022-07-12 04:53 UTC, Serxule commented
i say keep the crawl speed atleast a little bit faster, but not by a lot, maybe 4 or 4.5, what are the downsides anyways?

2022-07-15 18:22 UTC, nednaZ requested changes
Their balance may be a bit of a mess, since anyone can just lay down and start slipping people.

2022-07-15 18:25 UTC, dwasint commented on code/datums/components/snail_crawl.dm
> +			OT.MakeSlippery(TURF_WET_LUBE, min_wet_time = 10, wet_time_to_add =5)
i think its balanced as is they move at half speed, so giving them a lube floor that they can realistically only apply to 2 tiles before they vanish is okay, Plus you can just out walk a snail regardless of crawling or not

2022-08-07 17:46 UTC, closed without merging