Assistant ID of lower quality
Monkestation/MonkeStation pull request #546
Opened 2022-07-14 17:22 UTC by etherware-novice

# About The Pull Request
(catglove fix vers)
Nanotrasen has decided to start reusing id cards that the clown has destroyed, to save production costs. Assistants got the short end of the stick, being the least respected (and worst) job.

## Why It's Good For The Game
Assistant hate is funny! Also helps make the id card less bland

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![as_idcard](https://user-images.githubusercontent.com/73374039/179044593-7f9597b8-acb8-4313-baa0-66d0d1d262e7.png)

</details>

## Changelog

:cl:
:imageadd: added the 'assistant' card sprite
tweak: makes assistants round-start with the new card
:tweak: adjusts the pda painter and syndicate agent card to use the new sprite
/:cl:

2022-07-14 17:23 UTC, etherware-novice commented
finally finally finally fixed catgloves.dmi

2022-07-14 17:50 UTC, nednaZ commented
I can immediately say I dislike the sprite.
It doesn't look like much of anything, it's as if you just drew over the base sprite without any rhyme or reason.

2022-07-14 18:19 UTC, NiftyRyanyan commented
If you wanted the “cheap stake” not feel you should have just given them  a hi my name is stickers with a few electronics glued on instead of proper ids

2022-07-14 18:22 UTC, etherware-novice commented
> If you wanted the “cheap stake” not feel you should have just given them a hi my name is stickers with a few electronics glued on instead of proper ids

OO good idea

2022-07-14 18:45 UTC, etherware-novice commented
![as_better](https://user-images.githubusercontent.com/73374039/179059297-0d31d41e-a16d-48ba-8fba-93e62b94499a.png)

this is perfect

2022-07-14 19:52 UTC, NanoCats commented
> this is perfect

It is rotated at an angle while all the other IDs in the game are horizontal

>:(

2022-07-14 19:54 UTC, etherware-novice commented
> r

its not supposed to be an *actual* id but just a paper slip with some writing and electronics

2022-07-14 22:28 UTC, Zonespace27 requested changes
Eh concept overall, not a fan

2022-07-14 22:28 UTC, Zonespace27 commented on code/modules/jobs/job_types/assistant.dm
> +	id = /obj/item/card/id/job/assistant
```suggestion
	id = /obj/item/card/id/job/assistant //MONKESTATION ADDITION
```

2022-07-15 18:27 UTC, nednaZ commented
Not a fan of either of the sprite options.

2022-07-15 18:27 UTC, closed without merging