MORE AI SPRITES OK?
Monkestation/MonkeStation pull request #549
Opened 2022-07-14 20:06 UTC by NanoCats

# About The Pull Request

- Adds a handful of Cool™ and Good™ sprites lovingly hand-stolen from /vg/station, 5 or 6 of them. 
- Mostly I just wanted the Anime Girl one because I like being cute but I found some other cool ones on my search so why the fuck not
- I hate every part of interacting with github
## Why It's Good For The Game

Variety is the something of something, some of these are really fuckin cool.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/14065903/179069434-494610ec-08cb-4be4-9da5-cd50e26512f0.png)
*I would have made this an animated gif if I cared and knew how 
† "Boy" skin not shown because it's pretty much identical to "Girl" with shorter hair and not smiling.

</details>

## Changelog

:cl:

imageadd: Added "Boxfort" "Terminal" "Girl" "Boy" "Hotdog" and "Yesman" skins for AI Enrichment purposes

/:cl:

2022-07-14 22:26 UTC, Zonespace27 requested changes
not a fan of the locker perspective cardboard box sprite, but eh

2022-07-14 22:26 UTC, Zonespace27 commented on code/_globalvars/lists/flavor_misc.dm
> +	"Weird",
```suggestion
    //MONKESTATION ADDITION START
	"Weird",
```
modular comments

2022-07-14 22:26 UTC, Zonespace27 commented on code/_globalvars/lists/flavor_misc.dm
> +	)))
```suggestion
	)))
	//MONKESTATION ADDITION END
```

2022-07-15 07:53 UTC, NanoCats commented
Ok it turns out the issue was client side it should be AoK now.

2022-07-15 18:42 UTC, NanoCats commented
> ai-boxfort-crash needs to be modified to ai-boxfort_dead inside ai.dmi

it is done

2022-07-15 19:08 UTC, nednaZ approved these changes
Looks good to me.
The boxfort one is a bit weird, but it works.

2022-07-15 19:12 UTC, NanoCats commented
> Looks good to me. The boxfort one is a bit weird, but it works.

Listen, really I just wanted this adorable thing but I decided to just hoover up the other ones that looked neat so it wasn't as much of a "snowflake" pr and also you gotta admit it's funny. 

![Sprite-0001-export](https://user-images.githubusercontent.com/14065903/179295249-01cb434d-e5d5-4077-a361-c0ac00569cae.gif)

2022-07-15 19:14 UTC, merged