Ports welding overlay from the other server
Monkestation/MonkeStation pull request #553
Opened 2022-07-15 04:14 UTC by etherware-novice

# About The Pull Request
Makes welding sparks appear when welding a wall, ported from Citadel Statio

## Why It's Good For The Game
More visual input

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
tweak: adds welding sparks
/:cl:

2022-07-15 04:43 UTC, etherware-novice commented
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15702

2022-07-15 18:38 UTC, nednaZ commented
Please put the PR you ported from in the base of the PR.
Also make the changelog an "add" rather than "tweak"

2022-07-15 18:43 UTC, nednaZ requested changes
Looks good outside of the extra variable.

2022-07-15 18:43 UTC, nednaZ commented on code/game/objects/items/tools/weldingtool.dm
> +/obj/item/weldingtool/use_tool(atom/target, mob/living/user, delay, amount, volume, datum/callback/extra_checks, skill_gain_mult)
We don't have 'skill_gain_mult' on this server.

2022-07-16 19:52 UTC, nednaZ approved these changes
Looks good to me.

2022-07-16 19:52 UTC, merged