The great gas expansion
Monkestation/MonkeStation pull request #609
Opened 2022-07-31 17:40 UTC by dwasint

# About The Pull Request
Adds a ton of new gases, aswell as methods of obtaining gases
adds cold fusion

will update with ports later

## Why It's Good For The Game
More stuff for atmos to do, the ability for atmos to get some actual gamer gear

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: freon, hydrogen, healium, dilithium, pluonium, halon, zauker, hexane as new gases
add: crystalizer you can now solidify gases into cool objects
add: metalic hydrogen, go forth atmosians and make an army armed with fireaxes
add: electrolyzer, used to make new gases check the tg wiki for a better idea
add: cold fusion
tweak: heat generation of some gases
/:cl:

2022-08-01 18:37 UTC, DoctorSquishy commented
https://www.youtube.com/watch?v=atuFSv2bLa8

2022-08-11 12:30 UTC, dwasint commented
i want this enough to work on it again

2022-08-31 20:11 UTC, nednaZ requested changes
This will be going into the next testmerge after the changes are made

2022-08-31 20:11 UTC, nednaZ commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +/datum/gas_reaction/halon_o2removal
Looks like they forgot an underscore
```suggestion
/datum/gas_reaction/halon_o2_removal
```

2022-08-31 20:37 UTC, dwasint commented on monkestation/code/datums/components/hot_ice.dm
> +	UnregisterSignal(parent, COMSIG_ATOM_FIRE_ACT)
forgor to rename the unregister

2022-08-31 20:45 UTC, dwasint commented on code/game/objects/items/stacks/bscrystal.dm
> +/obj/item/stack/ore/dilithium_crystal
our orm ignores it

2022-08-31 20:45 UTC, dwasint commented on code/game/objects/items/stacks/bscrystal.dm
> +/obj/item/stack/ore/dilithium_crystal
so do lathes

2022-09-10 17:19 UTC, nednaZ commented
Been getting reports of fusion not working in general, even from people that know it.

2022-09-17 17:38 UTC, nednaZ approved these changes
This apparently works and I haven't been seeing any issues.
Atmospherics will forever be a mystery, even if I read and understand the code.

2022-09-17 17:39 UTC, merged

2023-05-13 18:12 UTC, Ghilker commented
You could've at least posted the prs you're taking most of these from