custom soup and salads also deepfrying fix
Monkestation/MonkeStation pull request #632
Opened 2022-08-09 20:29 UTC by dwasint

# About The Pull Request
https://github.com/AetherStation/AetherStation13/pull/99

Fixes deep fried foods not taking carrying over reagents, fixes custom soups not existing and also not taking reagents from the bowl.

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Re-added custom soups.
fix: Deep frying correctly transfers food reagents again.
/:cl:

2022-08-12 17:52 UTC, nednaZ requested changes
Just get rid of the debug message, everything else seems fine

2022-08-12 17:52 UTC, nednaZ commented on code/datums/components/customizable_reagent_holder.dm
> +	message_admins("test")
Test message

2022-08-12 17:53 UTC, dwasint commented on code/datums/components/customizable_reagent_holder.dm
> +	message_admins("test")
removed

2022-08-19 19:28 UTC, nednaZ approved these changes
Debug message removed, looks fine to me

2022-08-19 19:28 UTC, merged