Fixes Grills
Monkestation/MonkeStation pull request #661
Opened 2022-08-18 20:30 UTC by dwasint

# About The Pull Request
https://github.com/tgstation/tgstation/pull/65833

## Why It's Good For The Game
Gotta grill

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
fixes: grills now work again
/:cl:

2022-08-19 18:35 UTC, nednaZ requested changes
After testing it, it seems like the original smoke creation and sound no longer exists.
There is also no way to check if it's done or not unless you take an item off the grill, which makes it impossible to put it back on the grill afterwards.

2022-08-19 18:35 UTC, nednaZ commented on code/modules/food_and_drinks/kitchen_machinery/grill.dm
> +			return
Remove this, since it won't matter if you grill something repeatedly

2022-08-19 18:41 UTC, dwasint commented
> After testing it, it seems like the original smoke creation and sound no longer exists. There is also no way to check if it's done or not unless you take an item off the grill, which makes it impossible to put it back on the grill afterwards.

smoke should still work i never touched that part of the code? as for sound no idea why it broke reverted it back however

2022-08-21 18:41 UTC, nednaZ approved these changes
Looks like it's working as intended

2022-08-21 18:41 UTC, merged