Adds two new illegal shuttles
Monkestation/MonkeStation pull request #713
Opened 2022-09-07 22:26 UTC by Sord213

# About The Pull Request
Adds two new illegal shuttles that can be bought if the console is emagged or hacked. 

First shuttle is a modified meta shuttle made out of bananium and filled with various clown npcs. I have no idea if these NPCs are balanced or should reasonably see the light of day but I'm letting jesus take the wheel at this point.

Second shuttle is a cluster of small emergency pods. Some are locked for command, security, or medical. All of them make you want to die.

## Why It's Good For The Game
More shuttles are fun. These shuttles are meant to cause you a little pain on the inside if they're bought and you have to experience on them but it's ok sometimes a little pain helps build character.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos (click here to see the pictures,  be advised the bananium shuttle is like a flashbang)</summary>

![2022 09 07-17 19 53](https://user-images.githubusercontent.com/71185626/188993697-c4042785-bad0-4b16-89e4-5e99a70b15b2.png)
![2022 09 07-17 20 00](https://user-images.githubusercontent.com/71185626/188993700-c9d7ef04-795a-4b21-8e2b-b92818e7e58b.png)

</details>

## Changelog

:cl:
add: Added two new illegal emergency shuttles. Collect them all!
/:cl:

2022-09-08 18:25 UTC, nednaZ commented
How does the pod swarm work once it launches?
Is the surrounding area still hyperspace, or regular space?

2022-09-10 23:23 UTC, Sord213 commented
I didn't change any behavior so probably hyperspace. It's intended to be somewhat painful if bought.

2022-09-11 18:07 UTC, nednaZ requested changes
Currently unable to load the shuttle due to runtime errors.
"Cannot execute null.canDock()."
My guess is that there is no marker that shows the docking location on the shuttle itself

2022-09-13 21:39 UTC, nednaZ requested changes
Still can't get the shuttles to load in properly.
They can be purchased, but the template doesn't seem to exist at all.

2022-09-15 19:21 UTC, nednaZ requested changes
Your issue was that the file path wasn't correct, I got the shuttles loading after making the changes I suggested.

Issue with the pods, they cut off at the point I've highlighted:
![ss+(2022-09-15+at+12 18 33)](https://user-images.githubusercontent.com/62958508/190491049-a068c146-e322-41d5-adda-05fee0d9b40c.png)

2022-09-15 19:21 UTC, nednaZ commented on monkestation/code/datums/shuttles.dm
> +	prefix = "monkestation/_maps/shuttles/"
```suggestion
	prefix = "_maps/shuttles/"
```

2022-09-15 19:21 UTC, nednaZ commented on monkestation/code/datums/shuttles.dm
> +	prefix = "monkestation/_maps/shuttles/"
```suggestion
	prefix = "_maps/shuttles/"
```

2022-09-15 20:00 UTC, nednaZ requested changes
Last change and it should be good.
Replace the turf passthrough with actual space tiles, so then people can jump between pods in mid flight rather than dropping out into hyperspace

2022-09-17 17:20 UTC, nednaZ approved these changes
Looks good to me.
Will add them as illegal shuttles into the config

2022-09-17 17:20 UTC, merged