Lets Science and Medbay build simian translators
Monkestation/MonkeStation pull request #774
Opened 2022-10-10 17:28 UTC by KoboldCommando

# About The Pull Request

This adds the MonkeTech AutoTranslator to the lathes in both science and medbay, available after the data theory research is done (it's a precursor to neural tech which I'd consider "after" translators, and also severely lacking in actual unlocks).

## Why It's Good For The Game

Simians who lose their translator are now less screwed, and we have a slightly less awkward solution to people who can't speak common.

Consideration could be given to whether this lessens the impact of foreigner, simian, ashwalkers and so on, but I think the required tech and build resources can be tweaked to handle that later if a more coherent design is undertaken.

## Changelog

:cl:
add: MonkeTech AutoTranslators can now be built in science and medbay after some basic research!  Rejoice, death-prone simians!
/:cl:

2022-10-10 17:34 UTC, polygoblyn commented
Hell yeah thanks kobs!

2022-10-11 22:39 UTC, nednaZ requested changes
Very minor request, just for code readability.

2022-10-11 22:39 UTC, nednaZ commented on code/modules/research/designs/electronics_designs.dm
> +/datum/design/monkeytranslator
```suggestion
/datum/design/monkey_translator
```

2022-10-11 22:39 UTC, nednaZ commented on code/modules/research/designs/electronics_designs.dm
> +	id = "monkeytranslator"
```suggestion
	id = "monkey_translator"
```

2022-10-11 22:39 UTC, nednaZ commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("bounty_pad", "bounty_pad_control", "monkeytranslator") //Monkestation edit
```suggestion
	design_ids = list("bounty_pad", "bounty_pad_control", "monkey_translator") //Monkestation edit
```

2022-10-12 17:42 UTC, KoboldCommando commented
Good catch, thank you, done!

2022-10-14 21:08 UTC, nednaZ approved these changes
Looks good to me

2022-10-14 21:08 UTC, merged