Ports painting improvements, admin painting managers, and some tgui elements
Monkestation/MonkeStation pull request #793
Opened 2022-10-19 19:21 UTC by KoboldCommando

# About The Pull Request

This is a port of https://github.com/tgstation/tgstation/pull/63170

- Paintings can now do stroke painting.
- Added painting management panel for admins.
- Paintings now display author's character name, year of painting, medium and patron when hung on wall.
- You can become new patron by paying more than the previous one.
- Added painter's palettes to library vendor. (Sprites by @Mickyan )

In addition, this adds a few items to the library vendor (based on tg's list).
Along the way I also ported some tgui elements from tg.  Namely, tgui_alert, tgui_input_text, and tgui_input_number.  I did not apply them to other cases where they could be used, but they should be ready to go.

## Why It's Good For The Game

- FAR less tedious painting will result in many more paintings!
- Painting credit is very nice
- We've had trouble administrating paintings and this should help
- Patronage should help slightly with all that useless money
- The new tgui popups are very nice and should now be easier to apply elsewhere

## Changelog

:cl:
add: Painting now supports strokes!  No more pixel by pixel clicking.
add: The library vendor has new items, including a painting palette to help with paintings!
add: You can now sign your paintings, and they will also display the time painted and medium used
add: You can now donate money to become a patron of a painting!  Or outbid the previous patron!
code: Ported some tgui elements
admin: There is now an admin button to manage paintings
/:cl:

2022-10-19 19:32 UTC, dwasint commented
how much of the tgui alert/ input list does this port? up to the modern prs or only the first prs?

2022-10-19 19:34 UTC, dwasint commented on code/controllers/subsystem/persistent_paintings.dm
> +/*
is this comment block an example of a stored painting? i'd add a comment clarifying that

2022-10-19 20:04 UTC, KoboldCommando commented
> how much of the tgui alert/ input list does this port? up to the modern prs or only the first prs?

It only ports just enough to make these features work.  You can see the files I brought over.  They're the latest versions though.

2022-10-24 19:05 UTC, nednaZ requested changes
I need the other ported PRs added to the description/credits as well, unless the TGUI changes were somehow a part of this.

Everything seems fine to me, but we'll need to testmerge this.

2022-10-24 19:14 UTC, KoboldCommando commented on code/game/objects/structures/artstuff.dm
> -
I... thought it had been.  That's weird.  Fixed!

2022-10-28 17:45 UTC, nednaZ commented on code/modules/art/paintings.dm
> +	to_chat(user,span_notice("Nanotrasen Trust Foundation thanks you for your contribution. You're now offical patron of this painting."))
Grammar and spelling.

```suggestion
	to_chat(user,span_notice("Nanotrasen Trust Foundation thanks you for your contribution. You're now the official patron of this painting."))
```.

2022-10-29 00:30 UTC, KoboldCommando commented
Fixed it so canvasses obtain their painting name immediately, rather than having to wait until they're hung.

2022-10-30 02:56 UTC, nednaZ commented
No issues found during testmerge.
Go buy a painting.

2022-10-30 02:57 UTC, merged