Adds whoopee cushions and makes it easier to add new farts
Monkestation/MonkeStation pull request #821
Opened 2022-11-09 22:42 UTC by KoboldCommando

# About The Pull Request

This adds a whoopee cushion, how in the world did we not have one yet?  It can be bought in the hacked library or theatre vendors, or in the clown costume crate.

It also moves all the fart messages to a .txt file so it's effortless to add more!  I added a few myself.

## Why It's Good For The Game

fart funne

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: you can now find whoopee cushions in the library and theatre vendors, prank your friends!
code: it's now super easy to add more messages for when people fart!
/:cl:

2022-11-11 19:15 UTC, nednaZ requested changes
No Sord farts at all.

2022-11-11 19:15 UTC, nednaZ commented on code/game/objects/items/toys.dm
> +	farts = list('monkestation/sound/effects/sordfart14.ogg', 'monkestation/sound/effects/sordfart17.ogg', 'monkestation/sound/effects/sordfart18.ogg', 'monkestation/sound/effects/sordfart20.ogg')
No.

2022-11-12 13:08 UTC, KoboldCommando commented
sord has been murdered, as commanded

2022-11-13 18:43 UTC, nednaZ requested changes
Sordfarts are still in the file changes

2022-11-25 19:12 UTC, nednaZ approved these changes
With the Sord destroyed, this is fine

2022-11-25 19:12 UTC, merged