Vehicles now rev and waddle
Monkestation/MonkeStation pull request #832
Opened 2022-11-16 05:15 UTC by KoboldCommando

# About The Pull Request

This makes vehicles by default rev and waddle similar to the clown car.  They're variables that can be turned off, so for instance the secway will rev but not waddle, and the bicycle will do neither

## Why It's Good For The Game

Makes vehicles more interesting and noticeable.  Also slightly disguises the clown car which may or may not lead to fun.  I felt the clown car revving and shaking wasn't necessarily idiosyncratic to it.  Sec riding down the hall revving their secway (I'm saying it's gas powered lol), or cargo ordering their ATVs and rattling down the hall amuse me.  I think it's a harmless but fun change.

## Changelog

:cl:
add: Vehicles are a bit more noisy and lively!
/:cl:

2022-12-16 03:31 UTC, nednaZ requested changes
Might be fun, though a bit of a weird change honestly

2022-12-16 03:31 UTC, nednaZ commented on code/modules/vehicles/ridden.dm
> +	var/engine_sound_length = 20 //Set this to the length of the engine sound
Seconds define

2022-12-16 03:31 UTC, nednaZ commented on code/modules/vehicles/ridden.dm
> +		AddComponent(/datum/component/waddling)
Needs to be removed on destroy

2022-12-16 16:26 UTC, KoboldCommando commented
Changes made!

2022-12-22 17:34 UTC, nednaZ approved these changes
Looks good to me

2022-12-22 17:34 UTC, merged