Gives black powder explosions sparks
Monkestation/MonkeStation pull request #842
Opened 2022-11-25 19:28 UTC by KoboldCommando

# About The Pull Request

This adds a particle emitter to black powder-originated explosions.  It looks similar to welding tool sparks.  It should happen any time you see the message about powder throwing sparks

## Why It's Good For The Game

No more weird cases of invisible explosions!  You should now be able to visually see where black powder is about to explode even if the bomber and reagent container are both moved away before the boom happens.

## Changelog

:cl:
add: Black powder now means it when it says that it's throwing sparks!
/:cl:

2022-11-25 21:01 UTC, nednaZ requested changes
I'd like pictures of this in the PR as well

2022-11-25 22:48 UTC, KoboldCommando commented on code/modules/reagents/chemistry/recipes/pyrotechnics.dm
> +		boom.turf.remove_emitter("explosion_spark")
Fixed.  I moved this call to immediately before the explosion processing.

2022-12-14 16:39 UTC, nednaZ requested changes
I'd like Borbop spoken to about this, I believe there is a proper lifespan argument to the emitter proc.
Would help with making sure these got removed properly.

2022-12-14 19:33 UTC, KoboldCommando commented
I spoke to Borbop.  I don't see an easy way to do this.  The actual time to detonation isn't actually tracked so it's hard to update when moving the emitter.  The position is tracked using a datum so I can't use vis_contents.  And the underlying issue was the fact that the atom may wind up deleted before the explosion should go off so I want to avoid using that.

He did say it should get culled even in the worst case scenario.

2022-12-16 03:35 UTC, merged